// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.bubble.domain;

import ar.com.bubble.domain.PM;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PM_Roo_Configurable {
    
    declare @type: PM: @Configurable;
    
}
