// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.bubble.domain;

import ar.com.bubble.domain.Tag;

privileged aspect Tag_Roo_JavaBean {
    
    public String Tag.getNombre() {
        return this.nombre;
    }
    
    public void Tag.setNombre(String nombre) {
        this.nombre = nombre;
    }
    
}
