// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.bubble.domain;

import ar.com.bubble.domain.Tweet;
import javax.persistence.Entity;

privileged aspect Tweet_Roo_Jpa_Entity {
    
    declare @type: Tweet: @Entity;
    
}
