// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package ar.com.bubble.domain;

import ar.com.bubble.domain.Validacion;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Validacion_Roo_Configurable {
    
    declare @type: Validacion: @Configurable;
    
}
